name: Release

on:
  push:
    tags: [ 'v[0-9]+.*' ]

jobs:
  create-release:
    name: 'Create GitHub release'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Create Release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: '' # FIXME fill later?

  binaries:
    name: 'Upload release binaries'
    needs: [ create-release ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2
      with: { flutter-version: '3.24.4' }
    - uses: dart-lang/setup-dart@v1
      with: { sdk: '3.5.4' }
    - uses: actions/setup-java@v1
      with: { java-version: '17' }
    - uses: oberhauser-dev/flutter-release-action@v0
      with:
        working-directory: ./src
        dry-run: false
        token: ${{ github.token }}
        app-version: ${{ github.ref_name }}
        tag: ${{ github.ref }}
        build-type: 'apk'
